version: "3.3"

services:
  orchestra-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 5002:2345
    volumes:
      - .:/debug_env
      - ../orchestra-parser:/orchestra-parser