kw = {
    "entity__declaration_prefix": ["let", "declare"],
    "entity__properties_prefix": "which",
    "entity__prop__hasDescription": "hasDescription",
    "entity__prop__hasTags": "hasTags",

    "orchestra": "Orchestra",
    "project": "Project",
    "requirement": "Requirement",
    "feature": "Feature",
    "release": "Release",
    "eventhandler": "EventHandler",
    "event": "Event",
    "test": "Test",
    "repository": "Repository",
    "member": "Member",
    "definition": "Definition",
    "issue": "Issue",
    "usecase": "UseCase",
    "task": "Task",
    "datastruct": "DataStruct",
    "deployment": "Deployment",
    "role": "Role",

    "orchestra_prop___extends": "extends",
    "orchestra_prop___hasOrchestras": "hasOrchestras",
    "orchestra_prop___hasProjects": "hasProjects",
    "orchestra_prop___hasRoles": "hasRoles",
    "orchestra_prop___hasMembers": "hasMembers",

    "project_prop___extends": "extends",
    "project_prop___of": "of",
    "project_prop___hasReleases": "hasReleases",
    "project_prop___hasRoles": "hasRoles",
    "project_prop___hasMembers": "hasMembers",
    "project_prop___hasRepositories": "hasRepositories",

    "requirement_prop___extends": "extends",
    "requirement_prop___expands": "expands",
    "requirement_prop___of": "of",
    "requirement_prop___excludes": "excludes",
    "requirement_prop___hasRequirements": "hasRequirements",
    "requirement_prop___hasSources": "hasSources",

    "feature_prop___extends": "extends",
    "feature_prop___expands": "expands",
    "feature_prop___from": "from",
    "feature_prop___hasRequirements": "hasRequirements",
    "feature_prop___implemented": "implemented",
    "feature_prop___hasUrls": "hasUrls",

    "release_prop___extends": "extends",
    "release_prop___of": "of",
    "release_prop___hasRequirements": "hasRequirements",
    "release_prop___supports": "supports",
    "release_prop___excludes": "excludes",
    "release_prop___hasStartDate": "hasStartDate",
    "release_prop___hasEndDate": "hasEndDate",
    "release_prop___hasReleaseDate": "hasReleaseDate",
    "release_prop___hasVersion": "hasVersion",
    "release_prop___hasNotes": "hasNotes",

    "eventhandler_prop___extends": "extends",
    "eventhandler_prop___on": "on",
    "eventhandler_prop___triggers": "triggers",

    "event_prop___extends": "extends",
    "event_prop___hasType": "hasType",
    "event_prop___hasRepositories": "hasRepositories",
    "event_prop___hasSources": "hasSources",

    "test_prop___extends": "extends",
    "test_prop___hasCommand": "hasCommand",
    "test_prop___targets": "targets",

    "repository_prop___extends": "extends",
    "repository_prop___hasUrl": "hasUrl",
    "repository_prop___hasGuests": "hasGuests",
    "repository_prop___hasDevelopers": "hasDevelopers",
    "repository_prop___hasMaintainers": "hasMaintainers",

    "member_prop___extends": "extends",
    "member_prop___hasHandles": "hasHandles",
    "member_prop___hasRoles": "hasRoles",

    "definition_prop___extends": "extends",
    "definition_prop___expands": "expands",
    "definition_prop___hasSources": "hasSources",
    "definition_prop___from": "from",
    "definition_prop___solves": "solves",

    "issue_prop___extends": "extends",
    "issue_prop___solvedby": "solvedBy",
    "issue_prop___relatedto": "relatedTo",
    "issue_prop___from": "from",

    "usecase_prop___extends": "extends",
    "usecase_prop___hasPrimaryactor": "hasPrimaryActor",
    "usecase_prop___hasActors": "hasActors",
    "usecase_prop___triggers": "triggers",

    "task_prop___extends": "extends",
    "task_prop___hasCommand": "hasCommand",
    "task_prop___hasUrls": "hasUrls",

    "deployment_prop___extends": "extends",
    "deployment_prop___hasType": "hasType",
    "deployment_prop___of": "of",
    "deployment_prop___hasIp": "hasIp",
    "deployment_prop___hasDomain": "hasDomain",
    "deployment_prop___hasPorts": "hasPorts",
    "deployment_prop___islive": "isLive",
    
    "role_prop___extends": "extends",
    "role_prop___hasStartdata": "hasStartData",
    "role_prop___hasEndDate": "hasEndDate",
    "role_prop___hasReponsabilities": "hasReponsabilities",
    "role_prop___of": "of",
}
