kw = {
    "entity_declaration_prefix": "let|declare",
    "entity_properties_prefix": "which",
    "entity_prop___hasdescription": "hasDescription",
    "entity_prop___hastags": "hasTags",    

    "orchestra": "Orchestra",
    "project": "Project",
    "requirement": "Requirement",
    "feature": "Feature",
    "release": "Release",
    "eventhandler": "EventHandler",
    "event": "Event",
    "test": "Test",
    "repository": "Repository",
    "member": "Member",
    "definition": "Definition",
    "issue": "Issue",
    "usecase": "UseCase",
    "task": "Task",
    "datastruct": "DataStruct",
    "deployment": "Deployment",
    "role": "Role",

    "orchestra_prop___extends": "extends",
    "orchestra_prop___hasorchestras": "hasOrchestras",
    "orchestra_prop___hasprojects": "hasProjects",
    "orchestra_prop___hasroles": "hasRoles",
    "orchestra_prop___hasmembers": "hasMembers",

    "project_prop___extends": "extends",
    "project_prop___of": "of",
    "project_prop___hasreleases": "hasReleases",
    "project_prop___hasroles": "hasRoles",
    "project_prop___hasmembers": "hasMembers",
    "project_prop___hasrepositories": "hasRepositories",

    "requirement_prop___extends": "extends",
    "requirement_prop___expands": "expands",
    "requirement_prop___of": "of",
    "requirement_prop___excludes": "excludes",
    "requirement_prop___hasrequirements": "hasRequirements",
    "requirement_prop___hassources": "hasSources",

    "feature_prop___extends": "extends",
    "feature_prop___expands": "expands",
    "feature_prop___from": "from",
    "feature_prop___hasrequirements": "hasRequirements",
    "feature_prop___implemented": "implemented",
    "feature_prop___hasurls": "hasUrls",

    "release_prop___extends": "extends",
    "release_prop___of": "of",
    "release_prop___hasrequirements": "hasRequirements",
    "release_prop___supports": "supports",
    "release_prop___excludes": "excludes",
    "release_prop___hasstartdate": "hasStartDate",
    "release_prop___hasenddate": "hasEndDate",
    "release_prop___hasreleasedate": "hasReleaseDate",
    "release_prop___hasversion": "hasVersion",
    "release_prop___hasnotes": "hasNotes",

    "eventhandler_prop___extends": "extends",
    "eventhandler_prop___on": "on",
    "eventhandler_prop___triggers": "triggers",

    "event_prop___extends": "extends",
    "event_prop___hastype": "hasType",
    "event_prop___hasrepositories": "hasRepositories",
    "event_prop___hassources": "hasSources",

    "test_prop___extends": "extends",
    "test_prop___hascommand": "hasCommand",
    "test_prop___targets": "targets",

    "repository_prop___extends": "extends",
    "repository_prop___hasurl": "hasUrl",
    "repository_prop___hasguests": "hasGuests",
    "repository_prop___hasdevelopers": "hasDevelopers",
    "repository_prop___hasmaintainers": "hasMaintainers",

    "member_prop___extends": "extends",
    "member_prop___hashandles": "hasHandles",
    "member_prop___hasroles": "hasRoles",

    "definition_prop___extends": "extends",
    "definition_prop___expands": "expands",
    "definition_prop___hassources": "hasSources",
    "definition_prop___from": "from",
    "definition_prop___solves": "solves",

    "issue_prop___extends": "extends",
    "issue_prop___solvedby": "solvedBy",
    "issue_prop___relatedto": "relatedTo",
    "issue_prop___from": "from",

    "usecase_prop___extends": "extends",
    "usecase_prop___hasprimaryactor": "hasPrimaryActor",
    "usecase_prop___hasactors": "hasActors",
    "usecase_prop___triggers": "triggers",

    "task_prop___extends": "extends",
    "task_prop___hascommand": "hasCommand",
    "task_prop___hasurls": "hasUrls",

    "deployment_prop___extends": "extends",
    "deployment_prop___hastype": "hasType",
    "deployment_prop___of": "of",
    "deployment_prop___hasip": "hasIp",
    "deployment_prop___hasdomain": "hasDomain",
    "deployment_prop___hasports": "hasPorts",
    "deployment_prop___islive": "isLive",
    
    "role_prop___extends": "extends",
    "role_prop___hasstartdate": "hasStartDate",
    "role_prop___hasenddate": "hasEndDate",
    "role_prop___hasreponsabilities": "hasReponsabilities",
    "role_prop___of": "of",
}
