v = {
    "v___entity__prop__hasdescription": "string_ml",
    "v___entity__prop__hastags": "list",
    "v___orchestra__prop__extends": "string",
    "v___orchestra__prop__hasorchestras": "list",
    "v___orchestra__prop__hasprojects": "list",
    "v___orchestra__prop__hasroles": "list",
    "v___orchestra__prop__hasmembers": "list",

    "v___project__prop__extends": "string",
    "v___project__prop__of": "string",
    "v___project__prop__hasreleases": "list",
    "v___project__prop__hasroles": "list",
    "v___project__prop__hasmembers": "list",
    "v___project__prop__hasrepositories": "list",

    "v___requirement__prop__extends": "string",
    "v___requirement__prop__expands": "list",
    "v___requirement__prop__of": "string",
    "v___requirement__prop__excludes": "list",
    "v___requirement__prop__hasrequirements": "list",
    "v___requirement__prop__hassources": "list",

    "v___feature__prop__extends": "string",
    "v___feature__prop__expands": "list",
    "v___feature__prop__from": "list",
    "v___feature__prop__hasrequirements": "list",
    "v___feature__prop__implemented": "boolean",
    "v___feature__prop__hasurls": "list",

    "v___release__prop__extends": "string",
    "v___release__prop__of": "string",
    "v___release__prop__hasrequirements": "list",
    "v___release__prop__supports": "list",
    "v___release__prop__excludes": "list",
    "v___release__prop__hasstartdate": "date",
    "v___release__prop__hasenddate": "date",
    "v___release__prop__hasreleasedate": "date",
    "v___release__prop__hasversion": "version",
    "v___release__prop__hasnotes": "string",

    "v___eventhandler__prop__extends": "string",
    "v___eventhandler__prop__on": "string",
    "v___eventhandler__prop__triggers": "string",

    "v___event__prop__extends": "string",
    "v___event__prop__hastype": "string",
    "v___event__prop__hasrepositories": "list",
    "v___event__prop__hassources": "list",

    "v___test__prop__extends": "string",
    "v___test__prop__hascommand": "string",
    "v___test__prop__targets": "list",

    "v___repository__prop__extends": "string",
    "v___repository__prop__hasurl": "string",
    "v___repository__prop__hasguests": "list",
    "v___repository__prop__hasdevelopers": "list",
    "v___repository__prop__hasmaintainers": "list",

    "v___member__prop__extends": "string",
    "v___member__prop__hashandles": "list",
    "v___member__prop__hasroles": "list",
    
    "v___definition__prop__extends": "string",
    "v___definition__prop__expands": "list",
    "v___definition__prop__hassources": "list",
    "v___definition__prop__from": "string",
    "v___definition__prop__solves": "list",

    "v___issue__prop__extends": "string",
    "v___issue__prop__solvedby": "list",
    "v___issue__prop__relatedto": "list",
    "v___issue__prop__from": "string",

    "v___usecase__prop__extends": "string",
    "v___usecase__prop__hasprimaryactor": "string",
    "v___usecase__prop__hasactors": "list",
    "v___usecase__prop__triggers": "list",

    "v___task__prop__extends": "string",
    "v___task__prop__hascommand": "list",
    "v___task__prop__hasurls": "list",

    "v___deployment__prop__extends": "string",
    "v___deployment__prop__hastype": "\"test\" | \"production\"",
    "v___deployment__prop__of": "string",
    "v___deployment__prop__hasip": "string",
    "v___deployment__prop__hasdomain": "string",
    "v___deployment__prop__hasports": "list",
    "v___deployment__prop__islive": "boolean",

    "v___role__prop__extends": "string",
    "v___role__prop__hasstartdate": "date",
    "v___role__prop__hasenddate": "date",
    "v___role__prop__hasreponsabilities": "list",
    "v___role__prop__of": "string"
}
